-- USERS table
create table users (
   id            number
      generated by default as identity
   primary key,
   name          varchar2(100) not null,
   email         varchar2(100) not null unique,
   password_hash varchar2(255) not null,
   role          varchar2(20) not null,
   full_name     varchar2(100),
   nid_photo     clob,
   phone         varchar2(20),
   address       varchar2(500),
   occupation    varchar2(100),
   profile_img   varchar2(255),
   bio           varchar2(2000)
);

-- Rooms table (first version)
create table rooms (
   id          number
      generated by default as identity
   primary key,
   user_id     number not null,
   title       varchar2(100),
   description varchar2(500),
   listed_date date default sysdate,
   constraint fk_rooms_user foreign key ( user_id )
      references users ( id )
         on delete cascade
);

-- Blog post table from user
create table blog_posts (
   id         number
      generated by default as identity
   primary key,
   user_id    number not null,
   title      varchar2(200),
   content    clob,
   created_at date default sysdate,
   constraint fk_blogposts_user foreign key ( user_id )
      references users ( id )
         on delete cascade
);

-- Messages table (latest version, after drop/recreate)
create table messages (
   id           number
      generated by default on null as identity
   primary key,
   sender_id    number not null,
   recipient_id number not null,
   message_text clob not null,
   sent_at      timestamp with time zone default current_timestamp not null,
   constraint fk_sender foreign key ( sender_id )
      references users ( id )
         on delete cascade,
   constraint fk_recipient foreign key ( recipient_id )
      references users ( id )
         on delete cascade
);

-- Announcement table
create table announcements (
   id        number
      generated by default as identity
   primary key,
   title     varchar2(255) not null,
   content   clob not null,
   posted_by varchar2(100),
   posted_at timestamp default current_timestamp
);


-- Seller table from users
create table sellers (
   seller_id  number
      generated by default as identity
   primary key,
   user_id    number unique not null,
   shop_name  varchar2(100),
   phone      varchar2(20),
   address    varchar2(255),
   created_at date default sysdate,
   constraint fk_sellers_user foreign key ( user_id )
      references users ( id )
         on delete cascade
);

-- Property table
create table properties (
   id          number
      generated by default as identity
   primary key,
   seller_id   number not null,
   title       varchar2(255),
   rent        number,
   description clob,
   amenities   clob,
   pros        clob,
   cons        clob,
   images      clob,
   location    locationn,
   created_at  date default sysdate,
   status      varchar2(50) default 'active' not null,
   saved_count number default 0 not null,
   views       number default 0 not null,
   constraint fk_properties_seller foreign key ( seller_id )
      references users ( id )
         on delete cascade
);

select table_name
  from user_tables;

drop table properties cascade constraints;


create or replace type locationn as object (
      house       varchar2(100),
      street      varchar2(200),
      area        varchar2(100),
      district    varchar2(100),
      postal_code varchar2(20)
);

select *
  from users;

select *
  from sellers;

select *
  from properties;

create or replace view property_view as
   select p.id as propert_id,
          p.seller_id,
          s.full_name as seller_name,
          s.address as seller_address,
          s.phone as seller_phone,
          p.title,
          p.rent,
          p.description,
          p.amenities,
          p.pros,
          p.cons,
          p.images,
          p.location,
          p.created_at,
          p.status,
          p.saved_count,
          p.views
     from properties p
     join users s
   on p.seller_id = s.id;


   select * FROM property_view;

   SELECT 
         propert_id,
         seller_id,
         seller_name,
         seller_address,
         seller_phone,
         title,
         rent,
         description,
         amenities,
         pros,
         cons,
         images,
         location,
         created_at,
         status,
         saved_count,
         views
       FROM property_view
       WHERE propert_id = '3';



SELECT * from PROPERTIES;


